name: bootstrap-python-packaging
description: |
  Installs setuptools, setuptools_scm, pip, wheel
author: KOLANICH
runs:
  using: "composite"
  steps:
    - run: echo ${{github.action_path}}
      shell: bash
    - run: bash ${{github.action_path}}/action.sh
      shell: bash  # fuck, this doesn't guarantee that the script is called with bash. Has to call bash explicitly

branding:
  icon: check-square
  color: green
